#!/bin/bash

deepspeed llava/train/train_unlearn_mem.py \
    --lora_enable True --lora_r 128 --lora_alpha 256 --mm_projector_lr 1.1e-5 \
    --deepspeed ./scripts/zero3.json \
    --model_name_or_path liuhaotian/llava-v1.5-7b \
    --version v1 \
    --retain_data_path retain_data.json \
    --forget_data_path forget_data.json \
    --image_folder ./image/ \
    --vision_tower openai/clip-vit-large-patch14-336 \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --bf16 True \
    --output_dir ./checkpoints/llava-unlearn-lora \
    --num_train_epochs 10 \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 50000 \
    --save_total_limit 1 \
    --learning_rate 1.1e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb\
    --unlearn_type "npo"\
    --rmu_layer_id 15\
    --rmu_steering_coeffs "10"\
    --rmu_llava_loss_weight 1.2\
    --rmu_retain_alpha 0\
    --npo_beta 0.7\
    --npo_forget_alpha 1.0\
    --npo_llava_loss_weight 1.0\
    --verbose True\
    --loss_dir "./checkpoints/llava-unlearn-lora/losses"
